brain_two/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("todos/", include("todos.urls")),
    path("", RedirectView.as_view(url="/todos")),
]

todos/urls.py
from django.urls import path

from todos.views import (TodoListView, TodoDetailView, TodoCreateView,)

urlpatterns = [
    path("", TodoListView.as_view(), name="todolists_list"),
    path("<int:pk>/", TodoDetailView.as_view(), name="todolist_detail"),
    path("create/", TodoCreateView.as_view(), name="todolist_create"),
    path("items/create/", TodoCreateView.as_view(), name="todoitem_create"),#TODO: Update view class
    path("<int:pk>/edit/", TodoCreateView.as_view(), name="todolist_edit"),#TODO: Create edit view
    path("<int:pk>/delete/", TodoCreateView.as_view(), name="todolist_delete"),#TODO: Update delete view
    path("items/<int:pk>/edit/", TodoCreateView.as_view(), name="todoitem_edit"),#TODO: Create item edit view
]

todos/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        "TodoList",
        related_name="items",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from todos.models import TodoList, TodoItem
from django.urls import reverse_lazy

# Create your views here.
class TodoListView(ListView):
    model = TodoList
    template_name = "todolists/list.html"

class TodoDetailView(DetailView):
    model = TodoList
    template_name = "todolists/detail.html"

class TodoCreateView(CreateView):
    model = TodoList
    template_name="todolists/create.html"
    fields = ["name"]
    success_url = reverse_lazy("todolists_list")

    #def form_valid(self, form):

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Brain Two - Todo Lists</title>
    </head>

    <body>
        <header>
            <h1>Todo Lists</h1>
        </header>
        {% block content %}
        {% endblock content %}
    </body>



</html>

todos/templates/todoitems/create.html
{% extends 'base.html' %}

todos/templates/todolists/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <button class="button">Create</button>
        </div>
    </form>
</main>

{% endblock content %}

todos/templates/todolists/detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <a href="{% url 'todolist_edit' todolist.id %}">Edit List</a>
        <a href="{% url 'todolist_delete' todolist.id %}">Delete List</a>
    </div>
    {% for todoitem in todolist.items.all %}
    <a href="{% url 'todoitem_edit' todoitem.id %}">Edit Task</a>
    {% endfor %}
</main>

{% endblock content %}

todos/templates/todolists/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div>
        <a href="{% url 'todolist_create' %}">Create Todo List</a>
    </div>
    <div>
        <a href="{% url 'todoitem_create' %}">Create Todo Item</a>
    </div>
    {% for todolist in todolist_list %}
    <h2>
        <a href="{% url 'todolist_detail' todolist.id %}">{{ todolist.name }}</a>
    </h2>
    {% endfor %}
</main>

{% endblock content %}